apiVersion: v2
name: moodist
description: Ambient sounds for focus and calm.
home: https://github.com/plcnk/charts/tree/master/charts/moodist
icon: https://raw.githubusercontent.com/plcnk/charts/master/charts/moodist/icon.svg
type: application
version: 0.2.0
# renovate datasource=docker depName=ghcr.io/remvze/moodist
appVersion: "v1.5.1"
kubeVersion: ">=1.22.0-0"
keywords:
  - ambient
  - ambient-sounds
  - calm
  - white-noise
  - focus
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.5.0
sources:
  - https://github.com/remvze/moodist
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common helm release to v3.5.0
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/remvze/moodist
    - name: Chart Source
      url: https://github.com/plcnk/charts/tree/master/charts/moodist
