apiVersion: v2
name: wikijs
description: A modern, lightweight and powerful wiki app built on NodeJS.
home: https://github.com/plcnk/charts/tree/master/charts/wikijs
icon: https://raw.githubusercontent.com/plcnk/charts/master/charts/wikijs/icon.svg
type: application
version: 0.7.0
# renovate datasource=docker depName=ghcr.io/requarks/wiki
appVersion: "2.5.306"
kubeVersion: ">=1.22.0-0"
keywords:
  - wikijs
  - wiki
  - documentation
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.4.6
    condition: postgresql.enabled
sources:
  - https://github.com/Requarks/wiki
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common helm release to v3.7.1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/Requarks/wiki
    - name: Chart Source
      url: https://github.com/plcnk/charts/tree/master/charts/wikijs
