---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    # -- Controller type
    type: deployment
    # -- Number of desired pods
    replicas: 1
    containers:
      app:
        image:
          # -- Image repository
          repository: cloudflare/cloudflared
          # -- Image pull policy
          pullPolicy: IfNotPresent
          # -- Image tag
          tag: 2024.8.3

        # -- Environment variables
        # @default -- See [values.yaml](./values.yaml)
        env: {}
          # TZ: UTC

        securityContext:
          # -- Mount the container's root filesystem as read-only
          readOnlyRootFilesystem: true
          # -- Disable privilege escalations
          allowPrivilegeEscalation: false
          # -- Drop all capabilities
          capabilities:
            drop:
              - ALL

    pod:
      securityContext:
        # -- Run container as a non-root user
        runAsNonRoot: true
        # -- Run as `nobody` user
        runAsUser: 65534
        # -- Run as `nobody` group
        runAsGroup: 65534
        # -- Volume binds will be granted to `nobody` group
        fsGroup: 65534

    # -- Set the resource requests / limits for the container.
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

tunnel:
  # -- Set the Cloudflare Tunnel token here.
  #    Cannot coexist with `tunnel.existingSecret.enabled` set to `true`.
  token: "your-token-here"
  # -- You can set the token as an existing secret here.
  #    Cannot coexist with `tunnel.token`
  existingSecret:
    enabled: false
    name: ""
    key: ""

# -- Set the container log level.
#    Accepted values: `debug`, `info`, `warn`, `error`, `fatal`
logLevel: info

# -- Enable Metrics Monitor under this key.
metrics:
  enabled: false
  port: ""
