apiVersion: v1 
kind: ConfigMap
metadata:
  name: nginx-conf
data: 
  nginx.conf: |
    worker_processes  auto;

    error_log  /tmp/nginx/error.log warn;
    pid        /tmp/nginx/nginx.pid;

    events { 
      worker_connections  1024; 
    }

    http {
        include /etc/nginx/mime.types;
        
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ /index.html;
            }
        }
    }
